name: autoupdate
on:
  push:
    branches:
      - main
      - master
      - trunk
jobs:
  autoupdate:
    name: autoupdate
    runs-on: latest
    steps:
      - uses: docker://chinthakagodawita/autoupdate-action:v1.7.0
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
